using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;

namespace RuleBuilder.Rule {
	public class PasswordRule : RuleProperty, IPasswordGenerator {
		public PasswordRule() {
			void changeDelegate() {
				this.NotifyRuleChanged();
			}
			this.Components.CollectionChanged += (object _, NotifyCollectionChangedEventArgs args) => {
				changeDelegate();
				if (args.OldItems != null) {
					foreach (object item in args.OldItems) {
						((Component)item).RuleChanged -= changeDelegate;
					}
				}
				if (args.NewItems != null) {
					foreach (object item in args.NewItems) {
						((Component)item).RuleChanged += changeDelegate;
					}
				}
			};
		}
		public PasswordRule(PasswordRule other): this() {
			this.Length = other.Length;
			this.ExcludeCharacters = other.ExcludeCharacters;
			this.Components = new ObservableCollection<Component>(other.Components.Select((Component component) => new Component(component)));
		}
		private int __length = (int)KeePass.Program.Config.PasswordGenerator.AutoGeneratedPasswordsProfile.Length;
		public int Length {
			get => this.__length;
			set {
				if (this.__length != value) {
					this.__length = value;
					this.NotifyPropertyChanged(nameof(this.Length));
				}
			}
		}
		private string _excludeCharacters = string.Empty;
		public string ExcludeCharacters {
			get => this._excludeCharacters;
			set {
				if (this._excludeCharacters != value) {
					this._excludeCharacters = value;
					this.NotifyPropertyChanged(nameof(this.ExcludeCharacters));
				}
			}
		}
		private readonly ObservableCollection<Component> _components = new ObservableCollection<Component>();
		public ObservableCollection<Component> Components {
			get => this._components;
			set {
				this._components.Clear();
				foreach (Component component in value) {
					this._components.Add(component);
				}
			}
		}

		public string NewPassword() {
			List<string> password = new List<string>();
			foreach (Component component in this.Components.Where((Component component) => component.Required)) {
				HashSet<string> chars = CharacterClass.SplitString(component.CharacterClass?.Characters ?? string.Empty);
				foreach (string c in CharacterClass.SplitString(this.ExcludeCharacters)) {
					_ = chars.Remove(c);
				}
				if (chars.Count > 0) {
					password.Add(Random.RandomItem(chars));
				}
			}
			this.FillToLength(password);
			Random.Shuffle(password);
			return string.Join(string.Empty, password);
		}
		private void FillToLength(List<string> password) {
			if (password.Count >= this.Length) {
				return;
			}
			HashSet<string> allCharacters = this.AllCharacters();
			if (allCharacters.Count > 0) {
				while (password.Count < this.Length) {
					password.Add(Random.RandomItem(allCharacters));
				}
			}
			return;
		}
		private HashSet<string> AllCharacters() {
			HashSet<string> chars = new HashSet<string>();
			List<Component> components = this.Components.Where((Component component) => component.CharacterClass != null).ToList();
			foreach (string charSet in components.Count > 0 ?
				components.Select((Component component) => component.CharacterClass?.Characters ?? string.Empty)
				: new List<string>() { CharacterClass.AllCharacters.Characters }) {
				chars.UnionWith(CharacterClass.SplitString(charSet));
			}
			foreach (string c in CharacterClass.SplitString(this.ExcludeCharacters)) {
				_ = chars.Remove(c);
			}
			return chars;
		}
	}
}
